### PR TITLE
Added nanocomposite as subclass of nanomaterial

### PR DESCRIPTION
**Pull request by jmillanacosta**
Solves #523

### CODE REVIEW

**Comment by egonw** [comment]
Why not directly under nanomaterial, and next to http://purl.bioontology.org/ontology/npo#NPO_868 ?

**Review by egonw — COMMENTED** [review]
Why not directly under nanomaterial, and next to http://purl.bioontology.org/ontology/npo#NPO_868 ?

**Comment by jmillanacosta** [comment]
> Why not directly under nanomaterial, and next to http://purl.bioontology.org/ontology/npo#NPO_868 ?

I agree, when size of the composite is unknown classifying it as a nano-object (nano-structure) might not be ideal

**Comment by egonw** [comment]
Was adding 55 other terms intentional?

**Comment by jmillanacosta** [comment]
> Was adding 55 other terms intentional?

I am lost as to why the first commit https://github.com/enanomapper/ontologies/pull/525/commits/0a39ea0de953534cbd7a771f962c0ccc8886c99a  deleted them but shows no changes (see all these terms in `master` https://github.com/enanomapper/ontologies/blob/master/config/ncit.iris)

**Pull request merged**
