### PR TITLE
Adding NCIT_C67311

### PR DESCRIPTION
**Pull request by DeniseSl22**
https://github.com/enanomapper/ontologies/issues/292

@egonw

### CODE REVIEW

**Review by egonw — APPROVED** [review]
I will merge this is, but this is actually an example where we should also immediately send a PR to the Unit Ontology (UO).

**Comment by DeniseSl22** [comment]
@egonw : would you like me, or @jmillanacosta to send the PR to the Unit Ontology? We just discussed how to add terms to the eNanoMapper ontology :)

**Comment by egonw** [comment]
Yes, please do that. They're quite responsive

**Comment by DeniseSl22** [comment]
@egonw : @jmillanacosta and me just created a PR to the Unit Ontology: https://github.com/bio-ontology-research-group/unit-ontology/pull/59

**Comment by egonw** [comment]
Merged manually because of a merge conflict

**Pull request closed without merging**
